[package]
name = "nvim-config"
version = "0.1.0"
edition = "2024"

[lib]
name = "nvim_config"
crate-type = ["cdylib"]

[dependencies]
thiserror = "2.0.11"
nvim-api-helper = { path = "../nvim-api-helper" }
